import { IOpenMeteoRequest } from '@interfaces';

export const DefaultOpenMeteoRequest: IOpenMeteoRequest = {
    current_weather: {
        temperature: 0,
        weathercode: 0,
        winddirection: 0,
        windspeed: 0
    },
    daily: {
        apparent_temperature_max: [],
        apparent_temperature_min: [],
        et0_fao_evapotranspiration: [],
        precipitation_hours: [],
        precipitation_sum: [],
        rain_sum: [],
        shortwave_radiation_sum: [],
        showers_sum: [],
        snowfall_sum: [],
        sunrise: [],
        sunset: [],
        temperature_2m_max: [],
        temperature_2m_min: [],
        time: [],
        weathercode: [],
        winddirection_10m_dominant: [],
        windgusts_10m_max: [],
        windspeed_10m_max: []
    },
    daily_units: null,
    hourly: {
        apparent_temperature: [],
        cloudcover: [],
        cloudcover_high: [],
        cloudcover_low: [],
        cloudcover_mid: [],
        dewpoint_2m: [],
        diffuse_radiation: [],
        diffuse_radiation_instant: [],
        direct_normal_irradiance: [],
        direct_normal_irradiance_instant: [],
        direct_radiation: [],
        direct_radiation_instant: [],
        et0_fao_evapotranspiration: [],
        evapotranspiration: [],
        freezinglevel_height: [],
        precipitation: [],
        pressure_msl: [],
        rain: [],
        relativehumidity_2m: [],
        shortwave_radiation: [],
        shortwave_radiation_instant: [],
        showers: [],
        snow_depth: [],
        snowfall: [],
        soil_temperature_0cm: [],
        surface_pressure: [],
        temperature_2m: [],
        terrestrial_radiation: [],
        terrestrial_radiation_instant: [],
        time: [],
        vapor_pressure_deficit: [],
        visibility: [],
        weathercodev: [],
        winddirection_10m: [],
        windgusts_10m: [],
        windspeed_10m: [],
    },
    hourly_units: null,
    utc_offset_seconds: 0
};
